version: "3"
services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=your_database
    ports:
      - "8080:8080" # Example port mapping, adjust as needed
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
